### ISSUE TITLE
Improvements layout and UX

### ISSUE THREAD

**Issue by tgmarinho** [ConfyApp/support#1]
Hi guys! Nice project!

Maybe you should consider these things:

* Put a mailto attribute for your email and use API WhatsApp for send a message quickly
[Example](https://api.whatsapp.com/send?phone=55(067)%99999-4700&text=Ol%C3%A1%20Brother%20Feliz%20anivers%C3%A1rio!%20Deus%20aben%C3%A7oe!!!)
![](https://i.ibb.co/2vBLL8L/Screen-Shot-2019-10-17-at-14-06-14.png)
* Put max-width for improving the appearance, it is very large nowadays. ![See](https://i.ibb.co/ySgBXcg/Screen-Shot-2019-10-17-at-14-05-48.png)
* Font of your footer social network is not good, is a blurry image:
![](https://i.ibb.co/tb1q3F0/Screen-Shot-2019-10-17-at-14-06-17.png)

This is it, no big deal! Great job until here

**Comment by jgcmarins** [comment]
Hello @tgmarinho!
We appreciate your feedback.
Thanks \o/

**Comment by luizawramos-zz** [comment]
Hey @tgmarinho 
Nice issue!! Your tips are really important to us :)

**Comment by socksrust** [comment]
<img width="1284" alt="Screen Shot 2019-10-18 at 17 40 26" src="https://user-images.githubusercontent.com/13947203/67127072-f3f53080-f1ce-11e9-9575-edd22602bb11.png">
<img width="355" alt="Screen Shot 2019-10-18 at 17 40 46" src="https://user-images.githubusercontent.com/13947203/67127073-f3f53080-f1ce-11e9-8fbe-ee5faf34c1b2.png">

**Comment by socksrust** [comment]
Regarding the event detail, we will redesign it in the next few days.
