### ISSUE TITLE
Horizontal scroll on landing page

### ISSUE THREAD

**Issue by gsasouza** [ConfyApp/support#2]
## Current behaviour

Landing page has a unexpected horizontal scroll
![image](https://user-images.githubusercontent.com/8701003/67042210-c9877280-f0fd-11e9-824b-51a7e8b643d9.png)

## Expected behaviour

Should not have a  unexpected horizontal scroll. This issue is caused by an overflow in image on header 

## Steps to reproduce
1. Open Landing Page
2.
3.

### Products

- [x] web
- [ ] app

# Suggested solution
Change image width to 100% instead 100vw, when vertical scroll bar appear, image has an overflow
![image](https://user-images.githubusercontent.com/8701003/67042515-69dd9700-f0fe-11e9-9822-83fa0d7d35aa.png)

**Comment by luizawramos-zz** [comment]
Cool @gsasouza! Thanks for your advice  :)

**Comment by socksrust** [comment]
Awesome, thanks @gsasouza

**Comment by jgcmarins** [comment]
Fixed, thanks
