### ISSUE TITLE
Add some Transactional emails, e.g. when attending and cancelling attendance

### ISSUE THREAD

**Issue by joaopslins** [ConfyApp/support#5]
Receiving an email when doing some actions like confirming or cancelling attendance would be nice. Confirmation of the user actions by email improves UX.

**Comment by jgcmarins** [comment]
Thanks for bringing this up.
Engagement is one of our top priorities features.

**Comment by joaopslins** [comment]
No worries @jgcmarins , looking forward for the evolution of this app :rocket: 

Also related, adding a Notifications section on profile so the user can choose which notifications he/she should receive. Maybe some users would want that.

**Comment by jgcmarins** [comment]
Few of those engagement features were added.
Now you're able to discuss on events: https://twitter.com/confy_app/status/1206616768141287424
