### ISSUE TITLE
URL shortener to share easily

### ISSUE THREAD

**Issue by nicholasess** [ConfyApp/support#6]
## Description
Add URL shortener in Org and Events, because the link is very large

## Possible Implementations
Show modal with link to share or send a email to owner

**Comment by jgcmarins** [comment]
Thanks @nicholasess \o/

We plan to have slug for events, something like this: `https://confy.app/event/my-awesome-event`

**Comment by nicholasess** [comment]
@jgcmarins nice man

**Comment by jgcmarins** [comment]
Slugs were added. Next step is a URL shortener. Thanks
