### ISSUE TITLE
If has a problem with facebook login show infinite loading

### ISSUE THREAD

**Issue by daniloab** [ConfyApp/support#7]
## Current behavior
When I try to do login by facebook, it tells me that my e-mail is not confirmed, so can't continue with the login flow. 

After the error message, the screen goes into infinite loading without redirecting to any route.

<img width="1438" alt="Screen Shot 2019-10-21 at 10 25 40" src="https://user-images.githubusercontent.com/19939822/67209125-2d0aec00-f3ed-11e9-9b59-8a9b88573ca3.png">

## Expected behavior
I think that after this could bring back the user to login page

## Steps to reproduce
1. Login by facebook (should be facebook with e-mail unconfirmed)
2. See the message error
3. See the infinite login

### Products

- [x] web
- [ ] app

**Comment by AugustoCalaca** [comment]
@daniloab thanks for your feedback

**Comment by jgcmarins** [comment]
we'll release soon another social auth besides facebook
thanks

**Comment by daniloab** [comment]
Nice, @jgcmarins o/

**Comment by jgcmarins** [comment]
Fixed on production. Thanks.
