### ISSUE TITLE
Back button on 'Create Org' is not working

### ISSUE THREAD

**Issue by wendelfreitas** [ConfyApp/support#8]
## Current behaviour
When i try to create a org after see all orgs, i try to click 'back' button to see all orgs again, 'back' not working expected

## Expected behaviour
On i click back button in 'create org' page, back to the all orgs list

## Steps to reproduce
1. Authenticate with facebook 
2. Click **Orgs** in menu
3. Click on **Create Org**
4. Click on **Back** button

### Products

- [x] web
- [ ] app

**Comment by jgcmarins** [comment]
Thanks for the report, @wendelfreitas.
We'll release a fix soon.

**Comment by jgcmarins** [comment]
Fixed on production. Thanks.
